server:
  port: 8081

spring:
  application:
    name: receiver-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      default-binder: rabbit
      binders:
        rabbit:
          type: rabbit
      function:
        definition: messageCheck;messageStatus
      rabbit:
        bindings:
          messageStatus-out-0:
            producer:
              exchange-type: direct
              binding-routing-key: message-status
              routing-key-expression: '"message-status"'
              transacted: true
          messageCheck-in-0:
            consumer:
              binding-routing-key: message-check
              exchange-type: direct
              auto-bind-dlq: true
              republish-to-dlq: true
              requeue-rejected: true
              dead-letter-exchange: message
              dead-letter-queue-name: "message.message-check.dlq"
      bindings:
        messageStatus-out-0:
          destination: message
        messageCheck-in-0:
          group: message-check
          destination: message
          consumer:
            max-attempts: 5

