server:
  port: 8081

spring:
  application:
    name: receiver-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      pollable-source: messageCheck
      default-binder: rabbit
      binders:
        rabbit:
          type: rabbit
      rabbit:
        bindings:
          messageCheck-in-0:
            consumer:
              exchange-type: direct
              binding-routing-key: message-check
              transacted: true
              auto-bind-dlq: true
              dead-letter-queue-name: "message.message-check.dlq"
          message-status-out-0:
            producer:
              exchange-type: direct
              transacted: true
              binding-routing-key: message-status
              routing-key-expression: '"message-status"'
              destination: message
      bindings:
        messageCheck-in-0:
          group: message-check
          destination: message
        message-status-out-0:
          destination: message
      output-bindings:  message-status

