server:
  port: 8085

spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  cloud:
    stream:
      default-binder: rabbit
      binders:
        rabbit:
          type: rabbit
      function:
        definition: messageCheck;messageStatus
      rabbit:
        bindings:
          messageCheck-out-0:
            producer:
              exchange-type: direct
              binding-routing-key: message-check
              routing-key-expression: '"message-check"'
              transacted: true
          messageStatus-in-0:
            consumer:
              exchange-type: direct
              binding-routing-key: message-status
              auto-bind-dlq: true
              republish-to-dlq: true
              requeue-rejected: true
              dead-letter-exchange: message
              dead-letter-queue-name: "message.message-status.dlq"
      bindings:
        messageCheck-out-0:
          destination: message
        messageStatus-in-0:
          group: message-status
          destination: message
          consumer:
            max-attempts: 5
